/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.pro.luciene.bibliotecapessoal.view;

/**
 *
 * @author lucienecavalcanti
 */
public class JFPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFPrincipal
     */
    public JFPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpPrincipal = new javax.swing.JDesktopPane();
        jmPrincipal = new javax.swing.JMenuBar();
        jmiCadastros = new javax.swing.JMenu();
        jmiCategorias = new javax.swing.JMenuItem();
        jmiTipos = new javax.swing.JMenuItem();
        jmiObras = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmiSair = new javax.swing.JMenuItem();
        jmiMovimentos = new javax.swing.JMenu();
        jmiEmprestimos = new javax.swing.JMenuItem();
        jmiDevolucoes = new javax.swing.JMenuItem();
        jmiRelatorios = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jmiCadastros.setText("Cadastros");

        jmiCategorias.setText("Categorias");
        jmiCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCategoriasActionPerformed(evt);
            }
        });
        jmiCadastros.add(jmiCategorias);

        jmiTipos.setText("Tipos");
        jmiTipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiTiposActionPerformed(evt);
            }
        });
        jmiCadastros.add(jmiTipos);

        jmiObras.setText("Obras");
        jmiObras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiObrasActionPerformed(evt);
            }
        });
        jmiCadastros.add(jmiObras);
        jmiCadastros.add(jSeparator1);

        jmiSair.setText("Sair");
        jmiCadastros.add(jmiSair);

        jmPrincipal.add(jmiCadastros);

        jmiMovimentos.setText("Movimentos");

        jmiEmprestimos.setText("Empréstimos");
        jmiMovimentos.add(jmiEmprestimos);

        jmiDevolucoes.setText("Devoluções");
        jmiMovimentos.add(jmiDevolucoes);

        jmPrincipal.add(jmiMovimentos);

        jmiRelatorios.setText("Relatórios");
        jmPrincipal.add(jmiRelatorios);

        setJMenuBar(jmPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jdpPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jdpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCategoriasActionPerformed
        JIFCategorias janela = new JIFCategorias();
        jdpPrincipal.add(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_jmiCategoriasActionPerformed

    private void jmiTiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiTiposActionPerformed
        JIFTipos janela = new JIFTipos();
        jdpPrincipal.add(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_jmiTiposActionPerformed

    private void jmiObrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiObrasActionPerformed
        JIFObras janela = new JIFObras();
        jdpPrincipal.add(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_jmiObrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JDesktopPane jdpPrincipal;
    private javax.swing.JMenuBar jmPrincipal;
    private javax.swing.JMenu jmiCadastros;
    private javax.swing.JMenuItem jmiCategorias;
    private javax.swing.JMenuItem jmiDevolucoes;
    private javax.swing.JMenuItem jmiEmprestimos;
    private javax.swing.JMenu jmiMovimentos;
    private javax.swing.JMenuItem jmiObras;
    private javax.swing.JMenu jmiRelatorios;
    private javax.swing.JMenuItem jmiSair;
    private javax.swing.JMenuItem jmiTipos;
    // End of variables declaration//GEN-END:variables
}
